const database = [
  // {
  //   id: 109,
  //   img: "./images1/sneakers1.jpg",
  //   img2: "./images1/sneakers1.jpg",
  //   img3: "./images1/sneakers1.jpg",
  //   img4: "./images1/sneakers14.jpg",
  //   img5: "./images1/sneakers14.jpg",
  //   company: "Nike",
  //   title: "Nike SuperSonic",
  //   color: "Green",
  //   category: "sneakers",
  //   prevPrice: "2000",
  //   newPrice: "1700",
  // },
  // {
  //   id: 110,
  //   img: "./images/shoes1.jpg",
  //   img2: "./images/shoes1a.webp",
  //   img3: "./images/shoes1b.jpg",
  //   img4: "./images/shoes1c.jpg",
  //   img5: "./images/shoes1d.jpg",
  //   img6: "./images/shoes1e.jpg",
  //   company: "Campus",
  //   title: "Sports Running",
  //   color: "white",
  //   category: "sports",
  //   prevPrice: "1500",
  //   newPrice: "700",
  // },
  // {
  //   id: 111,
  //   img: "./images1/sports11.jpg",
  //   img2: "./images1/sports12.jpg",
  //   img3: "./images1/sports13.jpg",
  //   img4: "./images1/sports14.jpg",
  //   img5: "./images1/sports15.jpg",
  //   company: "Adidas",
  //   title: "snaple shoes",
  //   color: "gray",
  //   category: "sports",
  //   prevPrice: "1500",
  //   newPrice: "9999",
  // },
  // {
  //   id: 112,
  //   img: "./images1/sports21.jpg",
  //   img2: "./images1/sports22.jpg",
  //   img3: "./images1/sports23.jpg",
  //   img4: "./images1/sports24.jpg",
  //   company: "Puma",
  //   title: "Reveal shoes",
  //   color: "white",
  //   category: "sports",
  //   prevPrice: "9999",
  //   newPrice: "599",
  // },
  // {
  //   id: 113,
  //   img: "./images1/sports31.jpg",
  //   img2: "./images1/sports32.jpg",
  //   img3: "./images1/sports33.jpg",
  //   img4: "./images1/sports34.jpg",
  //   img5: "./images1/sports35.jpg",
  //   company: "Wood land",
  //   title: "Campus blue shoes",
  //   color: "blue",
  //   category: "sports",
  //   prevPrice: "1500",
  //   newPrice: "9999",
  // },
  // {
  //   id: 114,
  //   img: "./images1/sports41.jpg",
  //   img2: "./images1/sports42.jpg",
  //   img3: "./images1/sports43.jpg",
  //   img4: "./images1/sports44.jpg",
  //   img5: "./images1/sports45.jpg",
  //   company: "Nike",
  //   title: "Nike running shoes",
  //   color: "white",
  //   category: "sports",
  //   prevPrice: "1500",
  //   newPrice: "9999",
  // },
  // {
  //   id: 115,
  //   img: "./images1/sports51.jpg",
  //   img2: "./images1/sports52.jpg",
  //   img3: "./images1/sports53.jpg",
  //   img4: "./images1/sports54.jpg",
  //   img5: "./images1/sports55.jpg",
  //   company: "Woodland",
  //   title: "Army sports shoes",
  //   color: "gray",
  //   category: "sports",
  //   prevPrice: "1500",
  //   newPrice: "9999",
  // },
  // {
  //   id: 116,
  //   img: "./images1/formals11.jpg",
  //   img2: "./images1/formals12.jpg",
  //   img3: "./images1/formals13.jpg",
  //   img4: "./images1/formals14.jpg",
  //   img5: "./images1/formals15.jpg",
  //   company: "Adidas",
  //   title: " Formal office shoes",
  //   color: "red",
  //   category: "formals",
  //   prevPrice: "1500",
  //   newPrice: "9999",
  // },
  // {
  //   id: 117,
  //   img: "./images1/formals21.jpg",
  //   img2: "./images1/formals22.jpg",
  //   img3: "./images1/formals23.jpg",
  //   img4: "./images1/formals24.jpg",
  //   img5: "./images1/formals25.jpg",
  //   company: "Puma",
  //   title: " Formal casual shoes",
  //   color: "red",
  //   category: "formals",
  //   prevPrice: "1500",
  //   newPrice: "9999",
  // },
  // {
  //   id: 118,
  //   img: "./images1/formals31.jpg",
  //   img2: "./images1/formals32.jpg",
  //   img3: "./images1/formals33.jpg",
  //   img4: "./images1/formals34.jpg",
  //   img5: "./images1/formals35.jpg",
  //   company: "Woodland",
  //   title: " Mytaco Formal shoes",
  //   color: "gray",
  //   category: "formals",
  //   prevPrice: "1500",
  //   newPrice: "9999",
  // },
  // {
  //   id: 119,
  //   img: "./images1/formals41.jpg",
  //   img2: "./images1/formals42.jpg",
  //   img3: "./images1/formals43.jpg",
  //   img4: "./images1/formals44.jpg",
  //   img5: "./images1/formals45.jpg",
  //   company: "Nike",
  //   title: " Formal women's shoes",
  //   color: "red",
  //   category: "formals",
  //   prevPrice: "1500",
  //   newPrice: "9999",
  // },
  // {
  //   id: 120,
  //   img: "./images1/formals51.jpg",
  //   img2: "./images1/formals52.jpg",
  //   img3: "./images1/formals53.jpg",
  //   img4: "./images1/formals54.jpg",
  //   company: "Puma",
  //   title: " Formal women's shoes",
  //   color: "blue",
  //   category: "formals",
  //   prevPrice: "1500",
  //   newPrice: "9999",
  // },
  // {
  //   id: 121,
  //   img: "./images1/heels11.jpg",
  //   img2: "./images1/heels12.jpg",
  //   img3: "./images1/heels13.jpg",
  //   img4: "./images1/heels14.jpg",
  //   company: "Puma",
  //   title: " Women's heels white",
  //   color: "white",
  //   category: "heels",
  //   prevPrice: "1500",
  //   newPrice: "9999",
  // },
  // {
  //   id: 122,
  //   img: "./images1/heels21.jpg",
  //   img2: "./images1/heels22.jpg",
  //   img3: "./images1/heels23.jpg",
  //   img4: "./images1/heels24.jpg",
  //   company: "Adidas",
  //   title: " Women's heels clasic",
  //   color: "black",
  //   category: "heels",
  //   prevPrice: "1500",
  //   newPrice: "9999",
  // },
  // {
  //   id: 123,
  //   img: "./images1/heels31.jpg",
  //   img2: "./images1/heels32.jpg",
  //   img3: "./images1/heels33.jpg",
  //   img4: "./images1/heels34.jpg",
  //   company: "Nike",
  //   title: " Women's heels weightless",
  //   color: "red",
  //   category: "heels",
  //   prevPrice: "1500",
  //   newPrice: "9999",
  // },
  // {
  //   id: 124,
  //   img: "./images1/heels41.jpg",
  //   img2: "./images1/heels42.jpg",
  //   img3: "./images1/heels43.jpg",
  //   img4: "./images1/heels44.jpg",
  //   company: "Puma",
  //   title: " Women's party heels ",
  //   color: "red",
  //   category: "heels",
  //   prevPrice: "1500",
  //   newPrice: "9999",
  // },
  // {
  //   id: 125,
  //   img: "./images1/heels51.jpg",
  //   img2: "./images1/heels52.jpg",
  //   img3: "./images1/heels53.jpg",
  //   img4: "./images1/heels54.jpg",
  //   img5: "./images1/heels55.jpg",
  //   company: "woodland",
  //   title: " Women's style  heels ",
  //   color: "white",
  //   category: "heels",
  //   prevPrice: "1500",
  //   newPrice: "9999",
  // },
  // {
  //   id: 126,
  //   img: "./images1/sneakers11.jpg",
  //   img2: "./images1/sneakers12.jpg",
  //   img3: "./images1/sneakers13.jpg",
  //   img4: "./images1/sneakers14.jpg",
  //   company: "Nike",
  //   title: " Rockstar sneakers ",
  //   color: "black",
  //   category: "sneakers",
  //   prevPrice: "1500",
  //   newPrice: "9999",
  // },
  // {
  //   id: 127,
  //   img: "./images1/sneakers21.jpg",
  //   img2: "./images1/sneakers22.jpg",
  //   img3: "./images1/sneakers23.jpg",
  //   img4: "./images1/sneakers24.jpg",
  //   company: "Puma",
  //   title: " Lightening sneakers ",
  //   color: "white",
  //   category: "sneakers",
  //   prevPrice: "1500",
  //   newPrice: "9999",
  // },
  // {
  //   id: 128,
  //   img: "./images1/sneakers31.jpg",
  //   img2: "./images1/sneakers32.jpg",
  //   img3: "./images1/sneakers33.jpg",
  //   img4: "./images1/sneakers34.jpg",
  //   img5: "./images1/sneakers35.jpg",
  //   company: "Woodland",
  //   title: " Leather sneakers ",
  //   color: "red",
  //   category: "sneakers",
  //   prevPrice: "1500",
  //   newPrice: "9999",
  // },
  // {
  //   id: 129,
  //   img: "./images1/sneakers41.jpg",
  //   img2: "./images1/sneakers42.jpg",
  //   img3: "./images1/sneakers43.jpg",
  //   img4: "./images1/sneakers44.jpg",
  //   company: "Adidas",
  //   title: " Casual sneakers ",
  //   color: "blue",
  //   category: "sneakers",
  //   prevPrice: "1500",
  //   newPrice: "9999",
  // },
  // {
  //   id: 130,
  //   img: "./images1/sneakers51.jpg",
  //   img2: "./images1/sneakers52.jpg",
  //   img3: "./images1/sneakers53.jpg",
  //   img4: "./images1/sneakers54.jpg",
  //   img5: "./images1/sneakers55.jpg",
  //   company: "Nike",
  //   title: " Comfort sneakers ",
  //   color: "white",
  //   category: "sneakers",
  //   prevPrice: "1500",
  //   newPrice: "9999",
  // },
];

export default database;
